/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemasolar;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tipografias.Fuente;
/**
 *
 * @author yared
 */

public class CodigoBinario extends javax.swing.JFrame {
    Fuente tipofuentes;
    String Code[] = new String[50];
    String CodigoArr[] = new String[8];
    String cadenaCifrado="", cadenaCorrecta="";
    String Resultado="";
    int contLgh=0;
    String cadena="";
    String codigo="";
    String Cifrar="";
    int ceros, total=0;
    int conta=1, numC=0;
    char descifrado,cifrado;
    int caracter, totalCifrado;
    String Contraseña;
    /**
     * Creates new form CodigoBinario
     */
    public CodigoBinario() {
        initComponents();
        this.setSize(450, 430);
        tipofuentes = new Fuente();
    //    tf_codigo.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 16));
        btnDescifrar.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 10));
        btnReiniciar.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 10));
        btnCifrar.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 10));
        btnPegar.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 10));
       // tf_resultado.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 16));
    }
    
    public void ConvertirLetras(){
        cadenaCifrado="";
        cadenaCorrecta="";
        cifrado=Cifrar.charAt(numC);
        caracter=(int)(cifrado);
        for (int i = 0; i < 7; i++) {
            totalCifrado=caracter%2;
            caracter=caracter/2;
            System.out.println(caracter);
            cadenaCifrado=cadenaCifrado+totalCifrado;
        }
        cadenaCifrado=cadenaCifrado+"0";
        for (int i = 7; i >= 0; i--) {
            cadenaCorrecta=cadenaCorrecta+cadenaCifrado.charAt(i);
        }
        Resultado=Resultado+cadenaCorrecta;
        System.out.println(Resultado);
    }
    
    public void Llenar(){
           if(!codigo.isEmpty()){
                if(codigo.length()<8){
                   for (int i = 0; i < codigo.length(); i++) {
                    CodigoArr[i]=""+codigo.charAt(i);
                   }
                   for (int i = codigo.length(); i < 8; i++) {
                    CodigoArr[i]=""+0;
                   }
                   codigo="";
                }else{
                    for (int i = 0; i < 8; i++)
                    {
                    CodigoArr[i]=""+codigo.charAt(i);
                    }
                    codigo=codigo.substring(8, codigo.length());  
                }
            }
            for (int i = 0; i < CodigoArr.length; i++) 
            {
                System.out.println("arreglo["+i+"]="+CodigoArr[i]);
            }
    }
    
    public void Convertir(){
        total=0;
        conta=1;
        for (int i = 7; i >= 0; i--) {
            ceros=Integer.parseInt(CodigoArr[i]);
            ceros=ceros*conta;
            total=total+ceros;
            conta=conta*2;
        }  
    }
    
    public void Comparar(){
         
         try{
             llamar();
         }catch(NumberFormatException Letras){
             JOptionPane.showMessageDialog(rootPane, "Solo numeros como 0 y 1 para descifrar, no letras");
             tf_codigo.setText("");
             tf_codigo.requestFocus();
             tf_resultado.setText("");
         }
         
    }
    
    public void llamar(){
            Llenar();
            Convertir();
            descifrado=(char)(total);
            cadena=cadena+descifrado;
    }
    
    public void Codigo(){
        Code[0]="01000001";//A
        Code[1]="01000010";//B
        Code[2]="01000011";//C
        Code[3]="01000100";//D
        Code[4]="01000101";//E
        Code[5]="01000110";//F
        Code[6]="01000111";//G
        Code[7]="01001000";//H
        Code[8]="01001001";//I
        Code[9]="01001010";//J
        Code[10]="01001011";//K
        Code[11]="01001100";//L
        Code[12]="01001101";//M
        Code[13]="01001110";//N
        Code[14]="01001111";//O
        Code[15]="01010000";//P
        Code[16]="01010001";//Q
        Code[17]="01010010";//R
        Code[18]="01010011";//S
        Code[19]="01010100";//T
        Code[20]="01010101";//U
        Code[21]="01010110";//V
        Code[22]="01010111";//W
        Code[23]="01011001";//X
        Code[24]="01011010";//Z
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDescifrar = new javax.swing.JButton();
        tf_codigo = new javax.swing.JTextField();
        tf_resultado = new javax.swing.JTextField();
        btnReiniciar = new javax.swing.JButton();
        btnCifrar = new javax.swing.JButton();
        btnPegar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Codigo Binario");

        btnDescifrar.setText("Descifrar");
        btnDescifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescifrarActionPerformed(evt);
            }
        });

        tf_resultado.setEditable(false);

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        btnCifrar.setText("Cifrar Codigo");
        btnCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCifrarActionPerformed(evt);
            }
        });

        btnPegar.setText("Pegar");
        btnPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPegar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnPegar)
                .addGap(18, 18, 18)
                .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(tf_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescifrarActionPerformed
        cadena="";
        codigo=tf_codigo.getText();
        Comparar();
        while(!codigo.isEmpty()){
            llamar();
        }
        tf_resultado.setText(cadena);
    }//GEN-LAST:event_btnDescifrarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
        tf_codigo.setText("");
        tf_codigo.requestFocus();
        tf_resultado.setText("");
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void btnCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCifrarActionPerformed
        // TODO add your handling code here:
        numC=0;
        Resultado="";
        Cifrar=tf_codigo.getText();
        while(numC<Cifrar.length()){
            ConvertirLetras();
            numC++;
        }
        tf_resultado.setText(Resultado);
    }//GEN-LAST:event_btnCifrarActionPerformed

    private void btnPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegarActionPerformed
        try {
            // TODO add your handling code here:
            RandomAccessFile codigo = new RandomAccessFile("Codigo.txt", "rw");
            Contraseña=codigo.readLine();
            tf_codigo.setText(Contraseña);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "No hay nada que pegar");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_btnPegarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodigoBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodigoBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodigoBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodigoBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodigoBinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCifrar;
    private javax.swing.JButton btnDescifrar;
    private javax.swing.JButton btnPegar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_resultado;
    // End of variables declaration//GEN-END:variables
}
