/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sistemasolar;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author yared
 */
public class EnergiaPuerta extends javax.swing.JDialog {

    /**
     * Creates new form EnergiaPuerta
     */
    Icon imagen;
    Icon apagado;
   // Icon apagadoArr;
    int temp=15;
    int bloqueo=0;
    boolean izquierda, btntres;
    boolean btnU=false, btnD=false, btnC, btnS, btnN, btnOc, btnTc, btnQ;
    boolean btnCtr, btnSe, btnOch, btnDz, btnDc, btnCt, btnDs, btnDst, btnDo, btnDn; 
    boolean Puerta;
    Timer t = new Timer(100, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            temp++;
            Temperatura();
            pb_temperatura.setValue(temp);
        }
    });
    
    Timer Bloqueo = new Timer(100, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            bloqueo++;
            Cambios();
        }
    });
    
    public EnergiaPuerta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setSize(690, 430);
        this.setLocationRelativeTo(null);
//        t.start();
        Bloqueo.start();
    }
    
    public void MostrarFW(){
        btn4.setVisible(true);
        btn6.setVisible(true);
        btn8.setVisible(true);
        btn10.setVisible(true);
        btn12.setVisible(true);
        btn14.setVisible(true);
        btn16.setVisible(true);
        btn17.setVisible(true);
        btn18.setVisible(true);
        btn19.setVisible(true);
    }
    
    public void MostrarFarW(){
        btn5.setVisible(true);
        btn7.setVisible(true);
        btn9.setVisible(true);
        btn11.setVisible(true);
        btn13.setVisible(true);
        btn15.setVisible(true);
    }
    public void Firtsway(){
        izquierda=false;
        btn4.setVisible(false);
        btn6.setVisible(false);
        btn8.setVisible(false);
        btn10.setVisible(false);
        btn12.setVisible(false);
        btn14.setVisible(false);
        btn16.setVisible(false);
        btn17.setVisible(false);
        btn18.setVisible(false);
        btn19.setVisible(false);
    }
    
    public void Farway(){
        izquierda=true;
        btn5.setVisible(false);
        btn7.setVisible(false);
        btn9.setVisible(false);
        btn11.setVisible(false);
        btn13.setVisible(false);
        btn15.setVisible(false);
    }
    
    public void Cambios(){
        if(bloqueo==1){
                apagado = new ImageIcon(getClass().getResource("/imagenes/CambiosEIApagado.gif"));
                btn3.setIcon(apagado);
                Firtsway();
                MostrarFarW();
            } 
        if(bloqueo==6){
                apagado = new ImageIcon(getClass().getResource("/imagenes/CambiosEAApagado.gif"));
                btn3.setIcon(apagado);
                Farway();
                MostrarFW();
        }
        if(bloqueo>=11){
            bloqueo=0;
        }
    }
    
    
    
    
    public void Temperatura(){
        
        if(pb_temperatura.getValue()>=110){
//            t.stop();
//            this.dispose();
            JOptionPane.showMessageDialog(rootPane, "Temperatura alta");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn21 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        pb_temperatura = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn21ActionPerformed(evt);
            }
        });
        getContentPane().add(btn21);
        btn21.setBounds(0, 33, 80, 50);

        btn20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CambioFinalOff.gif"))); // NOI18N
        btn20.setBorderPainted(false);
        btn20.setContentAreaFilled(false);
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });
        getContentPane().add(btn20);
        btn20.setBounds(86, 33, 80, 50);

        btn13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaHapagada.gif"))); // NOI18N
        btn13.setBorderPainted(false);
        btn13.setContentAreaFilled(false);
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });
        getContentPane().add(btn13);
        btn13.setBounds(258, 33, 80, 50);

        btn15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaHapagada.gif"))); // NOI18N
        btn15.setBorderPainted(false);
        btn15.setContentAreaFilled(false);
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });
        getContentPane().add(btn15);
        btn15.setBounds(172, 33, 80, 50);

        btn19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaVApagada.gif"))); // NOI18N
        btn19.setBorderPainted(false);
        btn19.setContentAreaFilled(false);
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });
        getContentPane().add(btn19);
        btn19.setBounds(86, 89, 80, 50);

        btn17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaVApagada.gif"))); // NOI18N
        btn17.setBorderPainted(false);
        btn17.setContentAreaFilled(false);
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });
        getContentPane().add(btn17);
        btn17.setBounds(86, 201, 80, 50);

        btn16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CambioIzqArrOff.gif"))); // NOI18N
        btn16.setBorderPainted(false);
        btn16.setContentAreaFilled(false);
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });
        getContentPane().add(btn16);
        btn16.setBounds(86, 257, 80, 50);

        btn18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaVApagada.gif"))); // NOI18N
        btn18.setBorderPainted(false);
        btn18.setContentAreaFilled(false);
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });
        getContentPane().add(btn18);
        btn18.setBounds(86, 145, 80, 50);

        btn14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaHapagada.gif"))); // NOI18N
        btn14.setBorderPainted(false);
        btn14.setContentAreaFilled(false);
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });
        getContentPane().add(btn14);
        btn14.setBounds(172, 257, 80, 50);

        btn12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CambioAbjIzqOff.gif"))); // NOI18N
        btn12.setBorderPainted(false);
        btn12.setContentAreaFilled(false);
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });
        getContentPane().add(btn12);
        btn12.setBounds(258, 257, 80, 50);

        btn10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaVApagada.gif"))); // NOI18N
        btn10.setBorderPainted(false);
        btn10.setContentAreaFilled(false);
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn10);
        btn10.setBounds(258, 201, 80, 50);

        btn11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaHapagada.gif"))); // NOI18N
        btn11.setBorderPainted(false);
        btn11.setContentAreaFilled(false);
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn11);
        btn11.setBounds(344, 33, 80, 50);

        btn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaHapagada.gif"))); // NOI18N
        btn9.setBorderPainted(false);
        btn9.setContentAreaFilled(false);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn9);
        btn9.setBounds(430, 33, 80, 50);

        btn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CambioArrAbjOff.gif"))); // NOI18N
        btn8.setContentAreaFilled(false);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn8);
        btn8.setBounds(258, 145, 80, 50);

        btn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaHapagada.gif"))); // NOI18N
        btn6.setContentAreaFilled(false);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn6);
        btn6.setBounds(344, 145, 80, 50);

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaHapagada.gif"))); // NOI18N
        btn4.setContentAreaFilled(false);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn4);
        btn4.setBounds(430, 145, 80, 50);

        btn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CambioArribaOff.gif"))); // NOI18N
        btn7.setBorderPainted(false);
        btn7.setContentAreaFilled(false);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn7);
        btn7.setBounds(516, 33, 80, 50);

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CambiosEIApagado.gif"))); // NOI18N
        btn3.setBorderPainted(false);
        btn3.setContentAreaFilled(false);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn3);
        btn3.setBounds(516, 145, 80, 50);

        btn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaVApagada.gif"))); // NOI18N
        btn5.setBorderPainted(false);
        btn5.setContentAreaFilled(false);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn5);
        btn5.setBounds(516, 89, 80, 50);

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaVApagada.gif"))); // NOI18N
        btn2.setBorderPainted(false);
        btn2.setContentAreaFilled(false);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn2);
        btn2.setBounds(516, 201, 80, 50);

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistemasolar/EnergiaVApagada.gif"))); // NOI18N
        btn1.setBorderPainted(false);
        btn1.setContentAreaFilled(false);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(516, 257, 80, 50);

        pb_temperatura.setBackground(new java.awt.Color(204, 204, 204));
        pb_temperatura.setMaximum(130);
        getContentPane().add(pb_temperatura);
        pb_temperatura.setBounds(80, 330, 510, 17);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoEnergia1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn21ActionPerformed
        if(Puerta==true){
            t.stop();
            try {
                
                RandomAccessFile archivo =new RandomAccessFile("Puerta.txt", "rw");
                byte Open[]={'t', 'r', 'u', 'e'};
                archivo.write(Open);
                archivo.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EnergiaPuerta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(EnergiaPuerta.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "resuelve");
        }
        
    }//GEN-LAST:event_btn21ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        // TODO add your handling code here:
        Marte m = new Marte();
        if(btnQ==true){
            temp=temp+6;
            imagen = new ImageIcon(getClass().getResource("/imagenes/CambioFirstFinalON.gif"));
            btn20.setIcon(imagen);
            Puerta=true;
        }else if(btnDn==true){
            temp=temp+6;
            imagen = new ImageIcon(getClass().getResource("/imagenes/CambioFarFinalON.gif"));
            btn20.setIcon(imagen);
            Puerta=true;
        }
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        // TODO add your handling code here:
        if(btnOc==true){
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaHorizontal.gif"));
            btn13.setIcon(imagen);
            temp=temp+6;
            btnTc=true;
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        // TODO add your handling code here:
        if(btnTc==true){
            temp=temp+6;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaHorizontal.gif"));
            btn15.setIcon(imagen);
            btnQ=true;
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed
        // TODO add your handling code here:
        if(btnDo==true){
            temp=temp+3;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaVertical.gif"));
            btn19.setIcon(imagen);
            btnDn=true;
        }
    }//GEN-LAST:event_btn19ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        // TODO add your handling code here:
        if(btnDs==true){
            temp=temp+3;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaVertical.gif"));
            btn17.setIcon(imagen);
            btnDst=true;
        }
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        // TODO add your handling code here:
        if(btnCt==true){
            temp=temp+3;
            imagen = new ImageIcon(getClass().getResource("/imagenes/CambioIzqArrON.gif"));
            btn16.setIcon(imagen);
            btnDs=true;
        }
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        // TODO add your handling code here:
        if(btnDst==true){
            temp=temp+3;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaVertical.gif"));
            btn18.setIcon(imagen);
            btnDo=true;
        }
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        // TODO add your handling code here:
        if(btnDc==true){
            temp=temp+3;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaHorizontal.gif"));
            btn14.setIcon(imagen);
            btnCt=true;
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
        // TODO add your handling code here:
        if(btnDz==true){
            temp=temp+3;
            imagen = new ImageIcon(getClass().getResource("/imagenes/CambioAbjIzqON.gif"));
            btn12.setIcon(imagen);
            btnDc=true;
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        // TODO add your handling code here:
        if(btnOch==true){
            temp=temp+4;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaVertical.gif"));
            btn10.setIcon(imagen);
            btnDz=true;
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        // TODO add your handling code here:
        if(btnN==true){
            temp=temp+6;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaHorizontal.gif"));
            btn11.setIcon(imagen);
            btnOc=true;
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // TODO add your handling code here:
        if(btnS==true){
            temp=temp+6;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaHorizontal.gif"));
            btn9.setIcon(imagen);
            btnN=true;
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // TODO add your handling code here:
        if(btnSe==true){
            temp=temp+4;
            imagen = new ImageIcon(getClass().getResource("/imagenes/CambioArrAbjON.gif"));
            btn8.setIcon(imagen);
            btnOch=true;
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        if(btnCtr==true){
            temp=temp+4;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaHorizontal.gif"));
            btn6.setIcon(imagen);
            btnSe=true;
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        if(btntres==true){
            temp=temp+4;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaHorizontal.gif"));
            btn4.setIcon(imagen);
            btnCtr=true;
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        if(btnC==true){
            imagen = new ImageIcon(getClass().getResource("/imagenes/CambioArribaOn.gif"));
            btn7.setIcon(imagen);
            temp=temp+5;
            btnS=true;
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        if(btnD==true){
            if(izquierda==false){
                imagen = new ImageIcon(getClass().getResource("/imagenes/CambiosEnergiaArr.gif"));
                btn3.setIcon(imagen);
                Bloqueo.stop();
                btntres=true;
            } else if(izquierda==true){
                imagen = new ImageIcon(getClass().getResource("/imagenes/CambiosEnergiaIzq.gif"));
                btn3.setIcon(imagen);
                Bloqueo.stop();
                btntres=true;
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        if(btntres==true){
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaVertical.gif"));
            btn5.setIcon(imagen);
            temp=temp+5;
            btnC=true;
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        if(btnU==true){
            btnD=true;
            imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaVertical.gif"));
            btn2.setIcon(imagen);
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
        btnU=true;
        imagen = new ImageIcon(getClass().getResource("/imagenes/EnergiaVertical.gif"));
        btn1.setIcon(imagen);
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnergiaPuerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnergiaPuerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnergiaPuerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnergiaPuerta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EnergiaPuerta dialog = new EnergiaPuerta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar pb_temperatura;
    // End of variables declaration//GEN-END:variables
}
