/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package sistemasolar;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import tipografias.Fuente;
/**
 *
 * @author yared
 */
public class LocateCode extends javax.swing.JDialog {

   
    Fuente tipofuentes;
    private Clip clip;
    /**
     * Creates new form LocateCode
     * @param parent
     * @param modal
     */
    
    
    public LocateCode(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tipofuentes = new Fuente();
        this.setLocationRelativeTo(null);
        this.setSize(545, 388);
        lbTexto1.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 10));
        lbTexto2.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 10));
        lbTexto3.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 10));
        tf_Binario.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 20));
        btnGuardar.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 12));
        tf_Binario.setText("0110001101100101011000010111001101100101");
        btnRobbie.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CargarSonido("src/Audios/mireBro.wav");
                Reproducir();
            }
        });
    }

    public void CargarSonido(String ruta){
            try{
                File archivoSonido = new File(ruta);
                AudioInputStream audioinputstream = AudioSystem.getAudioInputStream(archivoSonido);
                clip = AudioSystem.getClip();
                clip.open(audioinputstream);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
    }
   
    public void Reproducir(){
        if(clip!=null){
            clip.setFramePosition(0);
            clip.start();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTexto3 = new javax.swing.JLabel();
        lbTexto2 = new javax.swing.JLabel();
        lbTexto1 = new javax.swing.JLabel();
        lbDialogo = new javax.swing.JLabel();
        tf_Binario = new javax.swing.JTextField();
        btnRobbie = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lbTexto3.setText("a la nave para descifrarlo.....");
        getContentPane().add(lbTexto3);
        lbTexto3.setBounds(170, 80, 310, 16);

        lbTexto2.setText("un cofre, pero esta en Binario, volvamos");
        getContentPane().add(lbTexto2);
        lbTexto2.setBounds(170, 60, 310, 16);

        lbTexto1.setText("Logre conseguir un codigo de acceso  a");
        getContentPane().add(lbTexto1);
        lbTexto1.setBounds(170, 40, 310, 16);

        lbDialogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dialogo2.gif"))); // NOI18N
        getContentPane().add(lbDialogo);
        lbDialogo.setBounds(157, 25, 340, 140);

        tf_Binario.setEditable(false);
        tf_Binario.setBackground(new java.awt.Color(204, 204, 204));
        tf_Binario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tf_Binario);
        tf_Binario.setBounds(30, 180, 476, 50);

        btnRobbie.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        btnRobbie.setForeground(new java.awt.Color(255, 255, 255));
        btnRobbie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Robbie.gif"))); // NOI18N
        btnRobbie.setBorderPainted(false);
        btnRobbie.setContentAreaFilled(false);
        getContentPane().add(btnRobbie);
        btnRobbie.setBounds(20, 30, 130, 120);

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(380, 250, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DialogoBinario.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String code="0110001101100101011000010111001101100101";
        try {
            RandomAccessFile Binario = new RandomAccessFile("Codigo.txt", "rw");
            byte codigo[]= new byte[code.length()];
            for (int i = 0; i < code.length(); i++) {
                codigo[i]=(byte)code.charAt(i);
            }
            Binario.write(codigo);
            Binario.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(LocateCode.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LocateCode.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LocateCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LocateCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LocateCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LocateCode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LocateCode dialog = new LocateCode(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRobbie;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDialogo;
    private javax.swing.JLabel lbTexto1;
    private javax.swing.JLabel lbTexto2;
    private javax.swing.JLabel lbTexto3;
    private javax.swing.JTextField tf_Binario;
    // End of variables declaration//GEN-END:variables
}
