/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemasolar;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import tipografias.Fuente;
/**
 *
 * @author yared
 */
public class PantalladeCarga extends javax.swing.JFrame {

    Fuente tipofuentes;
    private Clip clip;
    
    /**
     * Creates new form PantalladeCarga
     */
    public PantalladeCarga() {
        initComponents();
        this.setSize(580, 665);
        this.setLocationRelativeTo(null);
        tipofuentes = new Fuente();
        //cuerpo = new Fuentest();
        lb_Title.setFont(tipofuentes.fuente(tipofuentes.Crang, 0, 40));
        lb_Title1.setFont(tipofuentes.fuente(tipofuentes.Crang, 0, 30));
        btnStart.setFont(tipofuentes.fuente(tipofuentes.Crang, 0, 35));
        CargarSonido("src/Audios/PantalladeCarga.wav");
        Reproducir();
    }
    
    public void Puerta(){
        try {
            RandomAccessFile archivo = new RandomAccessFile("Puerta.txt", "rw");
            byte Reiniciar[]={'f','a','l','s','e'};
            archivo.write(Reiniciar);
            archivo.close();
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }
    
    public void CargarSonido(String ruta){
            try{
                File archivoSonido = new File(ruta);
                AudioInputStream audioinputstream = AudioSystem.getAudioInputStream(archivoSonido);
                clip = AudioSystem.getClip();
                clip.open(audioinputstream);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
    }
   
    public void Reproducir(){
        if(clip!=null){
            clip.setFramePosition(0);
            clip.start();
        }
    }
    
    public void VaciarInventario(){
        String vaciar="vacio_________________________________________________________________";
        try {
            RandomAccessFile inventario = new RandomAccessFile("Inventario.txt", "rw");
            byte Vaciando[] = new byte[vaciar.length()];
            for (int i = 0; i < vaciar.length(); i++) {
                Vaciando[i]=(byte)vaciar.charAt(i);
            }
            inventario.write(Vaciando);
            inventario.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PantalladeCarga.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PantalladeCarga.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_Title = new javax.swing.JLabel();
        lb_Title1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        lb_Title.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lb_Title.setForeground(new java.awt.Color(0, 0, 204));
        lb_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Title.setText("Across the Space");
        getContentPane().add(lb_Title);
        lb_Title.setBounds(30, 50, 520, 100);

        lb_Title1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lb_Title1.setForeground(new java.awt.Color(0, 0, 204));
        lb_Title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Title1.setText("KC20974");
        getContentPane().add(lb_Title1);
        lb_Title1.setBounds(70, 130, 410, 100);

        btnStart.setBackground(new java.awt.Color(0, 0, 0));
        btnStart.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        btnStart.setForeground(new java.awt.Color(255, 255, 255));
        btnStart.setText("START GAME");
        btnStart.setBorderPainted(false);
        btnStart.setContentAreaFilled(false);
        btnStart.setFocusPainted(false);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        getContentPane().add(btnStart);
        btnStart.setBounds(90, 340, 380, 120);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pantalla de carga.gif"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        clip.stop();
        Principal ventana = new Principal();
        ventana.setVisible(true);
        ventana.setSize(1080, 740);
        this.setVisible(false);
        Puerta();
        VaciarInventario();
    }//GEN-LAST:event_btnStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantalladeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantalladeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantalladeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantalladeCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantalladeCarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JLabel lb_Title1;
    // End of variables declaration//GEN-END:variables
}
