/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemasolar;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import tipografias.Fuente;


/**
 *
 * @author yared
 */
public class Principal extends javax.swing.JFrame {

    Fuente tipofuentes;
    private Clip clip;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setSize(1080, 730);
        this.setLocationRelativeTo(null);
        tipofuentes = new Fuente();
        btnSol.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 25));
        btnMarte.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 20));
        CargarSonido("src/Audios/MusicaPrincipal.wav");
        Reproducir();
    }

    public void CargarSonido(String ruta){
            try{
                File archivoSonido = new File(ruta);
                AudioInputStream audioinputstream = AudioSystem.getAudioInputStream(archivoSonido);
                clip = AudioSystem.getClip();
                clip.open(audioinputstream);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
    }
   
    public void Reproducir(){
        if(clip!=null){
            clip.setFramePosition(0);
            clip.start();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMarte = new javax.swing.JButton();
        btnSol = new javax.swing.JButton();
        btnMercurio = new javax.swing.JButton();
        btnVenus = new javax.swing.JButton();
        btnTierra = new javax.swing.JButton();
        lb_SistemaSolar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        btnMarte.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        btnMarte.setForeground(new java.awt.Color(0, 153, 153));
        btnMarte.setBorderPainted(false);
        btnMarte.setContentAreaFilled(false);
        btnMarte.setFocusPainted(false);
        btnMarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarteActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarte);
        btnMarte.setBounds(700, 200, 40, 40);

        btnSol.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        btnSol.setForeground(new java.awt.Color(0, 153, 153));
        btnSol.setBorderPainted(false);
        btnSol.setContentAreaFilled(false);
        btnSol.setFocusPainted(false);
        btnSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolActionPerformed(evt);
            }
        });
        getContentPane().add(btnSol);
        btnSol.setBounds(470, 320, 150, 150);

        btnMercurio.setFont(new java.awt.Font("Felix Titling", 3, 18)); // NOI18N
        btnMercurio.setForeground(new java.awt.Color(0, 153, 153));
        btnMercurio.setBorderPainted(false);
        btnMercurio.setContentAreaFilled(false);
        btnMercurio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMercurioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMercurio);
        btnMercurio.setBounds(460, 530, 50, 40);

        btnVenus.setFont(new java.awt.Font("Felix Titling", 3, 18)); // NOI18N
        btnVenus.setForeground(new java.awt.Color(0, 153, 153));
        btnVenus.setBorderPainted(false);
        btnVenus.setContentAreaFilled(false);
        btnVenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenusActionPerformed(evt);
            }
        });
        getContentPane().add(btnVenus);
        btnVenus.setBounds(420, 370, 30, 40);

        btnTierra.setFont(new java.awt.Font("Felix Titling", 3, 18)); // NOI18N
        btnTierra.setForeground(new java.awt.Color(0, 153, 153));
        btnTierra.setBorderPainted(false);
        btnTierra.setContentAreaFilled(false);
        btnTierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTierraActionPerformed(evt);
            }
        });
        getContentPane().add(btnTierra);
        btnTierra.setBounds(690, 500, 50, 50);

        lb_SistemaSolar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_SistemaSolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/SistemaSolarCompleto.gif"))); // NOI18N
        getContentPane().add(lb_SistemaSolar);
        lb_SistemaSolar.setBounds(0, -30, 1080, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolActionPerformed
        // TODO add your handling code here:
        Sol ventanita = new Sol();
        ventanita.setLocationRelativeTo(null);
        ventanita.setVisible(true);
        ventanita.setSize(1080, 670);
        this.setVisible(false);
        clip.stop();
    }//GEN-LAST:event_btnSolActionPerformed

    private void btnMercurioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMercurioActionPerformed
        // TODO add your handling code here:
        Mercurio ventanaMe = new Mercurio();
        ventanaMe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMercurioActionPerformed

    private void btnTierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTierraActionPerformed
        // TODO add your handling code here:
        Tierra ventanaT = new Tierra();
        ventanaT.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTierraActionPerformed

    private void btnVenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenusActionPerformed
        // TODO add your handling code here:
        Venus ventanaV = new Venus();
        ventanaV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVenusActionPerformed

    private void btnMarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarteActionPerformed
        // TODO add your handling code here:
        Marte M = new Marte();
        M.setVisible(true);
        this.setVisible(false);
        clip.stop();
    }//GEN-LAST:event_btnMarteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMarte;
    private javax.swing.JButton btnMercurio;
    private javax.swing.JButton btnSol;
    private javax.swing.JButton btnTierra;
    private javax.swing.JButton btnVenus;
    private javax.swing.JLabel lb_SistemaSolar;
    // End of variables declaration//GEN-END:variables
}
