/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemasolar;

import tipografias.Fuente;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import java.applet.AudioClip;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author yared
 */
public class Sol extends javax.swing.JFrame {
    
    Icon imagen;
    Fuente tipofuentes;
    int contseg=0;
    int contD=0, contC=0;
    private Clip clip;
    private Clip clipM;
            
    Timer t = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            contseg++;
            textoTiempo();
        }
    });

    /**
     * Creates new form Sol
     */
    public Sol() {
        initComponents();
        t.start();
        this.setSize(1080, 670);
        tipofuentes = new Fuente();
        lb_1.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 12));
        lb_2.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 12));
        lb_3.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 12));
        lb_4.setFont(tipofuentes.fuente(tipofuentes.RC, 0, 12));
        CargarSonido("src/Audios/Sol.wav");
        Reproducir();
        btnRobbie.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CargarSonidoM("src/Audios/mireBro.wav");
                ReproducirM();
            }
        });
    }

    public void Mostrar(){
            t.stop();
            lb_1.setVisible(false);
            lb_2.setVisible(false);
            lb_3.setVisible(false);
            lb_4.setVisible(false);
            btnDialogo.setVisible(false);
            btnRobbie.setVisible(false);
    }
    
    public void Dialogo1(){
            lb_1.setText("KC209, la radiacion que emite el Sol confunde a el LIGO,");
            lb_2.setText("haciendo que no se detecte radiacion de un lugar que ");
            lb_3.setText("no sea el Sol, ahora no intentes aterrizar en el Sol, no");
            lb_4.setText("es necesario explicar porque, asi que solo......");
    }
    
    public void Dialogo2(){
            lb_1.setText("observarlo de lejos para evitarnos problemas, espero ");
            lb_2.setText("hayas ledio estas indicaciones, ¿Por que no lo harias?...");
            lb_3.setText("verdad... ");
            lb_4.setText("bueno, te dejo -Robbie......");
    }
    public void textoTiempo(){
        if(contseg==10){
            Dialogo1();
            contD++;
            contC++;
        }else if(contseg==20){
            Dialogo2();
            contC++;
        }else if(contseg>30){
            Mostrar();
        }
    }
    
    public void CargarSonido(String ruta){
            try{
                File archivoSonido = new File(ruta);
                AudioInputStream audioinputstream = AudioSystem.getAudioInputStream(archivoSonido);
                clip = AudioSystem.getClip();
                clip.open(audioinputstream);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
    }
   
    public void Reproducir(){
        if(clip!=null){
            clip.setFramePosition(0);
            clip.start();
        }
    }
    
    public void CargarSonidoM(String ruta){
            try{
                File archivoSonido = new File(ruta);
                AudioInputStream audioinputstream = AudioSystem.getAudioInputStream(archivoSonido);
                clipM = AudioSystem.getClip();
                clipM.open(audioinputstream);
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, e);
            }
    }
   
    public void ReproducirM(){
        if(clipM!=null){
            clipM.setFramePosition(0);
            clipM.start();
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        btnBinario = new javax.swing.JButton();
        btnAterrizar = new javax.swing.JButton();
        btnRobbie = new javax.swing.JButton();
        lb_Control = new javax.swing.JLabel();
        lb_1 = new javax.swing.JLabel();
        lb_2 = new javax.swing.JLabel();
        lb_3 = new javax.swing.JLabel();
        lb_4 = new javax.swing.JLabel();
        btnDialogo = new javax.swing.JButton();
        lb_hawking = new javax.swing.JLabel();
        Lb_Sol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estrella Sol");
        setResizable(false);
        getContentPane().setLayout(null);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonVolver.gif"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(910, 480, 60, 80);

        btnBinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonBinario.gif"))); // NOI18N
        btnBinario.setContentAreaFilled(false);
        btnBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnBinario);
        btnBinario.setBounds(970, 400, 50, 70);

        btnAterrizar.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        btnAterrizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAterrizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BotonAterrizar.gif"))); // NOI18N
        btnAterrizar.setContentAreaFilled(false);
        btnAterrizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAterrizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAterrizar);
        btnAterrizar.setBounds(870, 400, 40, 70);

        btnRobbie.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        btnRobbie.setForeground(new java.awt.Color(255, 255, 255));
        btnRobbie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Robbie.gif"))); // NOI18N
        btnRobbie.setBorderPainted(false);
        btnRobbie.setContentAreaFilled(false);
        getContentPane().add(btnRobbie);
        btnRobbie.setBounds(50, 330, 130, 120);

        lb_Control.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Control.png"))); // NOI18N
        getContentPane().add(lb_Control);
        lb_Control.setBounds(830, 360, 230, 230);

        lb_1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lb_1.setText("Bien, llegamos a la estrella de nuestro Sistema, el sol ");
        getContentPane().add(lb_1);
        lb_1.setBounds(20, 470, 540, 17);

        lb_2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lb_2.setText(" lo que le da vida al planeta, funciona por medio de la");
        getContentPane().add(lb_2);
        lb_2.setBounds(20, 490, 540, 17);

        lb_3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lb_3.setText(" fusion nuclear, por lo que es peligroso acercarse ");
        getContentPane().add(lb_3);
        lb_3.setBounds(20, 510, 540, 17);

        lb_4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        lb_4.setText("mucho a el, no podemos investigar el paradero de...");
        getContentPane().add(lb_4);
        lb_4.setBounds(20, 530, 540, 17);

        btnDialogo.setFont(new java.awt.Font("Felix Titling", 3, 24)); // NOI18N
        btnDialogo.setForeground(new java.awt.Color(255, 255, 255));
        btnDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Dialogo1.gif"))); // NOI18N
        btnDialogo.setContentAreaFilled(false);
        btnDialogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDialogoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDialogo);
        btnDialogo.setBounds(10, 450, 560, 130);

        lb_hawking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Hawking.gif"))); // NOI18N
        lb_hawking.setText("jLabel1");
        getContentPane().add(lb_hawking);
        lb_hawking.setBounds(60, 130, 70, 50);

        Lb_Sol.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        Lb_Sol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sun (1).gif"))); // NOI18N
        getContentPane().add(Lb_Sol);
        Lb_Sol.setBounds(0, 0, 1080, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinarioActionPerformed
        // TODO add your handling code here:
        CodigoBinario ventanaB = new CodigoBinario();
        ventanaB.setVisible(true);
        ventanaB.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBinarioActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        clip.stop();
        Principal ventanaP = new Principal();
        ventanaP.setVisible(true);
        ventanaP.setSize(1080, 730);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnDialogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDialogoActionPerformed
        // TODO add your handling code here:
        
        if(contD==1){
            contD=contD+contC;
        }else{
        contD++;
        }
        switch (contD) {
            case 1 -> {
                Dialogo1();
                contC++;
                contseg=11;
            }
            case 2 -> {
                Dialogo2();
                contC++;
                contseg=21;
            }
            case 3 -> Mostrar();
            default -> {
            }
        }
    }//GEN-LAST:event_btnDialogoActionPerformed

    private void btnAterrizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAterrizarActionPerformed
        // TODO add your handling code here:
        Mostrar();
        imagen = new ImageIcon(getClass().getResource("/imagenes/SolAterrizaje.gif"));
        Lb_Sol.setIcon(imagen);
        btnAterrizar.setEnabled(false);
        lb_hawking.setVisible(false);
    }//GEN-LAST:event_btnAterrizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lb_Sol;
    private javax.swing.JButton btnAterrizar;
    private javax.swing.JButton btnBinario;
    private javax.swing.JButton btnDialogo;
    private javax.swing.JButton btnRobbie;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lb_1;
    private javax.swing.JLabel lb_2;
    private javax.swing.JLabel lb_3;
    private javax.swing.JLabel lb_4;
    private javax.swing.JLabel lb_Control;
    private javax.swing.JLabel lb_hawking;
    // End of variables declaration//GEN-END:variables
}
